# Generated by Django 5.2.6 on 2025-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
