# Generated by Django 5.2.6 on 2025-09-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_users_email_alter_users_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="email",
            new_name="username",
        ),
    ]
