# Generated by Django 5.2.6 on 2025-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_rename_email_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
