# Generated by Django 5.2.6 on 2025-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_users_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
